services:
  checkout:
    image: hexpm/elixir:1.17.2-erlang-27.0.1-debian-bookworm-20240812-slim
    working_dir: /src
    volumes:
      - type: bind
        source: ./checkout/src
        target: /src
      - /src/deps/
      - /src/_build/
    command: mix test
